### ISSUE TITLE
Negative values in Part (semi-partial) R2

### ISSUE THREAD

**Issue by maqian12** [mastoffel/partR2#1]
(1) I sometimes got negative values in part R2. Does it make sense? Is this a bug? Below is part of the output:
Part (semi-partial) R2:
 Predictor(s)                           R2      CI_lower CI_upper nboot ndf
 Model                                   0.4324  0.3672  0.4874   10    5  
 photoperiod                             0.3452  0.2800  0.4002   10    4  
 Force5s                                -0.0297 -0.0948  0.0254   10    4  
 Chill_5_5                               0.0106 -0.0545  0.0657   10    4  
 scPDSI_p                               -0.0107 -0.0759  0.0444   10    4  

(2) I can only install partR2 by setting "build_vignettes = FALSE". Does it affect the use of the partR2?

Look forward to your feedback. Thanks!

**Comment by mastoffel** [comment]
Yes, semi-partial R2 can become negative for predictors which explain very little. This is because it can happen that when a predictor is removed from the model, the overall R2 increases. We decided so far to not set them to 0, but this might change in the future. I wouldn't worry about this.

(2) No problem, this just means that the vignette (manual) is not installed. However, you can just download it directly from this GitHub repository, where it can be found in the vignettes/ folder.

We hopefully publish a paper soon with some more explanations.

**Comment by maqian12** [comment]
Thanks for your reply. 
Look forward to the paper on this package.
